services:
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data/
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
